In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn

In [2]:
# Input dataset (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [4]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [5]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

[tensor([[ 91.,  88.,  64.],
         [102.,  43.,  37.],
         [ 87., 134.,  58.],
         [ 73.,  67.,  43.],
         [ 69.,  96.,  70.]]), tensor([[ 81., 101.],
         [ 22.,  37.],
         [119., 133.],
         [ 56.,  70.],
         [103., 119.]])]

In [6]:
# Define instance of model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4534, -0.3589,  0.1862],
        [-0.4957, -0.4920, -0.4430]], requires_grad=True)
Parameter containing:
tensor([ 0.0860, -0.3194], requires_grad=True)


In [7]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [8]:
# Import nn.functional
import torch.nn.functional as F
# Define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(24156.3340, grad_fn=<MseLossBackward>)


In [9]:
#function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(pred, yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(model(inputs), targets))
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)

Training loss:  tensor(34.7473, grad_fn=<MseLossBackward>)


In [10]:
# Generate predictions
predcts = model(inputs)
predcts

tensor([[ 59.0129,  71.7256],
        [ 82.4487,  97.8036],
        [115.2533, 137.7632],
        [ 31.5755,  44.7188],
        [ 96.2275, 109.5533],
        [ 59.0129,  71.7256],
        [ 82.4487,  97.8036],
        [115.2533, 137.7632],
        [ 31.5755,  44.7188],
        [ 96.2275, 109.5533],
        [ 59.0129,  71.7256],
        [ 82.4487,  97.8036],
        [115.2533, 137.7632],
        [ 31.5755,  44.7188],
        [ 96.2275, 109.5533]], grad_fn=<AddmmBackward>)

In [11]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [12]:
class SimpleNet(nn.Module):
    # Initialize the layers
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(3, 3)
        self.act1 = nn.ReLU() # Activation function
        self.linear2 = nn.Linear(3, 2)
    
    # Perform the computation
    def forward(self, x):
        x = self.linear1(x)
        x = self.act1(x)
        x = self.linear2(x)
        return x
        
model = SimpleNet()
opt = torch.optim.SGD(model.parameters(), 1e-5)
loss_fn = F.mse_loss

In [13]:
fit(100, model, loss_fn, opt)

Training loss:  tensor(20.4891, grad_fn=<MseLossBackward>)
